#include "arduino_secrets.h"
/* =========================================================================
  Sketch generated by the Arduino IoT Cloud Thing
  
  Arduino IoT Cloud Variables description:
  int packet_id; 
  float water_do;
  float water_ph;
  float water_temperature;
  bool reset_packet_id; 
  =========================================================================
*/

#include "thingProperties.h"

// --- 1. HARDWARE PINS ---
// Define the Hardware Serial pins connected to the ATmega128A
#define RXD2 16
#define TXD2 17

// --- 2. COMMAND QUEUE FLAG ---
// This acts as the memory for the reset button. 
// If true, the ESP knows it needs to send a reset command the next time the ATmega wakes up.
bool pendingReset = false; 

/* =========================================================================
   ================================= SETUP =================================
   ========================================================================= */
void setup() {
  // Initialize Serial Monitor for human debugging via USB to your laptop
  Serial.begin(9600);

  // Initialize Hardware Serial 2 for machine communication with the ATmega128A
  Serial1.begin(9600, SERIAL_8N1, RXD2, TXD2);

  // Give the hardware 1.5 seconds to physically stabilize
  delay(1500);

  // Initialize cloud properties (Generated automatically by Arduino Cloud)
  initProperties();

  // Connect to Arduino IoT Cloud using your WiFi credentials
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  // Set debug level to 2 to see network connection details in the Serial Monitor
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

/* =========================================================================
   ============================== MAIN LOOP ================================
   ========================================================================= */
void loop() {
  // Process incoming cloud updates and keep the WiFi connection to the server alive
  ArduinoCloud.update();

  // --- 1. LISTEN TO THE ATMEGA ---
  // Check if the ATmega has sent a new string of text down the wire
  if (Serial1.available() > 0)
  {
    // Read the incoming text LINE BY LINE (up to the hidden 'Enter' key / \n)
    String rec = Serial1.readStringUntil('\n');
    
    // Remove any accidental hidden characters, spaces, or carriage returns
    rec.trim();

    // --- 2. THE FILTER ---
    // The ATmega prints human debug text AND machine telemetry on the same wire.
    // We only put the '_' character at the very end of the telemetry string.
    // If the line does NOT end with '_', the ESP silently deletes it and ignores it.
    if (rec.endsWith("_")) 
    {
      // Clean the string by deleting the '_' character so it doesn't break our math
      rec.replace("_", ""); 
      
      Serial.print("Clean Telemetry Found: ");
      Serial.println(rec);

      // Find the mathematical positions of the three commas to chop up the string
      int firstComma  = rec.indexOf(',');
      int secondComma = rec.indexOf(',', firstComma + 1);
      int thirdComma  = rec.indexOf(',', secondComma + 1);

      // Validate that the string actually contains 3 commas before trusting it
      if (firstComma != -1 && secondComma != -1 && thirdComma != -1)
      {
        // --- 3. THE DIGITAL SCISSORS ---
        // Extract the individual string segments between the commas
        String packetStr = rec.substring(0, firstComma);
        String tempStr   = rec.substring(firstComma + 1, secondComma);
        String phStr     = rec.substring(secondComma + 1, thirdComma);
        String doStr     = rec.substring(thirdComma + 1);

        // Convert the text strings into actual mathematical numbers
        long packetVal = packetStr.toInt();
        float tempVal  = tempStr.toFloat();
        float phVal    = phStr.toFloat();
        float doVal    = doStr.toFloat();

        // --- 4. UPDATE THE CLOUD DASHBOARD ---
        // Update the total packets sent tracking number
        packet_id = packetVal; 

        // Only update the cloud gauges if the sensor didn't send an error code (-1.0)
        // This prevents a dead sensor from wiping out the last known healthy value on your screen.
        if (tempVal != -1.0) { water_temperature = tempVal; }
        if (phVal != -1.0)   { water_ph = phVal; }
        if (doVal != -1.0)   { water_do = doVal; }
        
        Serial.println("Cloud Variables Updated Successfully.");

        // --- 5. FIRE THE QUEUED DASHBOARD COMMAND ---
        // Because the ATmega just successfully sent us data, we know 100% for a fact 
        // that it is wide awake and currently sitting in its 1.5-second listening window!
        if (pendingReset == true) {
            Serial.println(">>> ATmega is Awake! Firing queued reset command down the wire...");
            
            delay(100);
            // Send the command down the TX wire. MUST include \n so the ATmega knows the command is finished.
            Serial1.print("CMD_RESET_PACKET_ID\n");
            
            // Clear the internal queue so we don't spam the command forever
            pendingReset = false; 
            
            // ---> THE UI SWITCH FIX <---
            // Flip the cloud dashboard switch OFF. 
            // This visually confirms to you that the physical command has finally left the ESP!
            reset_packet_id = false; 
        }
      }
      else
      {
        Serial.println("Error: Commas missing from telemetry string.");
      }
    }
  }
}

/* =========================================================================
   ======================= CLOUD CALLBACK FUNCTIONS ========================
   ========================================================================= */

/*
  Since reset_packet_id is a READ_WRITE variable, this function is automatically
  triggered by the ESP every time you click the switch on your cloud dashboard.
*/
void onResetPacketIdChange()  {
  
  // If the dashboard switch was turned ON
  if (reset_packet_id == true) {
    
    // Flag the command into the queue
    Serial.println("Dashboard Command: Reset Queued! Waiting for ATmega to wake up...");
    pendingReset = true; 
    
    // Notice that reset_packet_id = false has been REMOVED from here.
    // The switch will now stay ON in your browser while it waits for the ATmega.
  }
}